# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('writer', 'Writer'), ('editor', 'Editor')], default='writer', max_length=255, verbose_name='Role'),
        ),
    ]
