# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('writer', 'Writer'), ('editor', 'Editor')], default='writer', max_length=255, null=True, verbose_name='Role'),
        ),
    ]
