# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Review'), ('approved', 'Approved')], default='new', max_length=255, verbose_name='Status')),
                ('article_url', models.URLField(blank=True, help_text='Url should point to google docs.', null=True, verbose_name='Article Url')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_articles', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='written_articles', to=settings.AUTH_USER_MODEL, verbose_name='Writer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
