# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('create_at',)},
        ),
    ]
